[package]
name = "integration-tests"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[test]]
name = "administration"
path = "administration.rs"

[[test]]
name = "health_check"
path = "health_check.rs"

[[test]]
name = "initialize_stablecoin"
path = "initialize_stablecoin.rs"

[[test]]
name = "issuance"
path = "issuance.rs"

[dev-dependencies]
amm = { path = "../programs/amm", features = ["no-entrypoint"] }
anchor-lang.workspace = true
anchor-spl.workspace = true
litesvm.workspace = true
solana-instruction.workspace = true
solana-instruction-error.workspace = true
solana-keypair.workspace = true
solana-message.workspace = true
solana-signer.workspace = true
solana-transaction.workspace = true
solana-transaction-error.workspace = true
stablecoin = { path = "../programs/stablecoin", features = ["no-entrypoint"] }
